export default {
  VBtn: {
    flat: true,
    variant: "flat",
    ripple: true,
  },
  VSwitch: {
    flat: true,
    density: "compact",
    baseColor: "switch",
    color: "surface-variant",
    minWidth: 32,
    variant: "flat",
    validateOn: "invalid-input",
    hideDetails: "auto",
    falseValue: false,
    ripple: false,
  },
  VRating: {
    density: "compact",
    color: "on-surface",
    activeColor: "surface-variant",
    ripple: false,
  },
  VForm: {
    validateOn: "invalid-input",
  },
  VCheckbox: {
    density: "compact",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
    ripple: false,
  },
  VTextField: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VTextarea: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VOtpInput: {
    variant: "outlined",
    baseColor: "on-surface-variant",
    validateOn: "invalid-input",
    autofocus: true,
  },
  VAutocomplete: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
    hideNoData: true,
  },
  VCombobox: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VChip: {
    closable: true,
    rounded: true,
    flat: true,
    ripple: false,
    variant: "flat",
    color: "highlight",
    density: "default",
  },
  VMenu: {
    closeOnBack: true,
    closeOnContentClick: true,
    locationStrategy: "connected",
    density: "compact",
  },
  VSpeedDial: {
    attach: true,
    closeOnBack: true,
    closeOnContentClick: true,
    location: "top",
    transition: "slide-y-reverse-transition",
  },
  VSelect: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    validateOn: "invalid-input",
    hideDetails: "auto",
  },
  VCard: {
    density: "compact",
    color: "background",
    flat: true,
    ripple: false,
  },
  VTab: {
    color: "on-surface",
    baseColor: "on-surface-variant",
    ripple: false,
  },
  VTabs: {
    grow: true,
    elevation: 0,
    color: "on-surface",
    bgColor: "secondary",
    baseColor: "secondary",
    sliderColor: "surface-variant",
  },
  VTable: {
    density: "comfortable",
  },
  VToolbar: {
    flat: true,
  },
  VListItem: {
    ripple: false,
  },
  VDataTable: {
    color: "background",
    itemsPerPage: -1,
    hover: true,
  },
  VDialog: {
    scrim: true,
    scrollable: true,
    retainFocus: true,
    transition: false,
  },
  VExpansionPanel: {
    tile: true,
    ripple: false,
  },
  VExpansionPanels: {
    flat: true,
    tile: true,
    static: true,
    variant: "accordion",
    bgColor: "secondary",
    ripple: false,
  },
  VProgressLinear: {
    height: 10,
    rounded: true,
    color: "surface-variant",
  },
};
