export default {
  VBtn: {
    flat: true,
    variant: "flat",
    ripple: true,
  },
  VSwitch: {
    flat: true,
    density: "compact",
    baseColor: "switch",
    color: "surface-variant",
    hideDetails: "auto",
    minWidth: 32,
    variant: "flat",
    falseValue: false,
    ripple: false,
  },
  VRating: {
    density: "compact",
    color: "on-surface",
    activeColor: "surface-variant",
    ripple: false,
  },
  VCheckbox: {
    density: "compact",
    color: "surface-variant",
    hideDetails: "auto",
    ripple: false,
  },
  VTextField: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    hideDetails: "auto",
  },
  VTextarea: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    hideDetails: "auto",
  },
  VOtpInput: {
    variant: "outlined",
    baseColor: "on-surface-variant",
    autofocus: true,
  },
  VAutocomplete: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    hideDetails: "auto",
    hideNoData: true,
  },
  VCombobox: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    hideDetails: "auto",
  },
  VSelect: {
    flat: true,
    variant: "solo-filled",
    color: "surface-variant",
    itemTitle: "text",
    itemValue: "value",
    hideDetails: "auto",
  },
  VCard: {
    density: "compact",
    color: "background",
    flat: true,
    ripple: false,
  },
  VTab: {
    color: "on-surface",
    baseColor: "on-surface-variant",
    ripple: false,
  },
  VTabs: {
    grow: true,
    elevation: 0,
    color: "on-surface",
    bgColor: "secondary",
    baseColor: "secondary",
    sliderColor: "surface-variant",
  },
  VTable: {
    density: "comfortable",
  },
  VListItem: {
    ripple: false,
  },
  VDataTable: {
    color: "background",
    itemsPerPage: -1,
    hover: true,
  },
  VExpansionPanel: {
    tile: true,
    ripple: false,
  },
  VExpansionPanels: {
    flat: true,
    tile: true,
    static: true,
    variant: "accordion",
    bgColor: "secondary-light",
    ripple: false,
  },
  VProgressLinear: {
    height: 10,
    rounded: true,
    color: "surface-variant",
  },
};
